[client]
showSidebarNavigation = false
toolbarMode = "minimal"
showErrorDetails = false

[ui]
hideTopBar = true

[browser]
gatherUsageStats = false

[server]
enableStaticServing = false

[global]
showWarningOnDirectExecution = false